name: "Integration Github Mattermost"
description: "Send a message (with optional attachments) to your Mattermost instance via API"
author: Singnet
inputs:
  server-url:
    description: "Base URL of the Mattermost server (e.g., https://mattermost.example.com)"
    required: true
  token:
    description: "Mattermost personal access token for authentication"
    required: true
  channel-id:
    description: "The ID of the Mattermost channel where the message will be posted"
    required: true
  message:
    description: "The text content of the message to send"
    required: true
  attachments-path:
    description: "Comma-separated list of file paths or directories to upload as attachments (optional)"
    required: false

branding:
  icon: "bell"
  color: "red"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    MATTERMOST_SERVER_URL: ${{ inputs.server-url }}
    MATTERMOST_TOKEN: ${{ inputs.token }}
    MATTERMOST_CHANNEL_ID: ${{ inputs.channel-id }}
    MATTERMOST_MESSAGE: ${{ inputs.message }}
    MATTERMOST_ATTACHMENTS_PATH: ${{ inputs.attachments-path }}
